ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.0
  hooks:
    - id: ruff
      args:
        - --fix
        - --show-fixes
        - --extend-select=B,I,RUF,UP
      types_or: [python, pyi, jupyter]
    - id: ruff-format
      types_or: [python, pyi, jupyter]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
    - id: mypy
      files: ^src
      args:
        #- --strict
        - --ignore-missing-imports
        #- --disallow-untyped-defs
        #- --check-untyped-defs

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args: ["-Lhist,gaus,nd"]
